
services:

  mongo:
    image: mongo:latest
    container_name: mongo_container_xox
    volumes:
      - /mongo_data/db:/data/db
    ports:
      - "27017:27017"
  app:
    build:
      context: .  
    ports:
      - "80:3000"  
    env_file:
      - ./.env
    depends_on:
      - mongo 
    restart: always 

volumes:
  mongo-data:  