name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t thashenu/xox:build-$GITHUB_RUN_NUMBER .

      # Step 3: Log in to Docker Hub
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u thashenu --password-stdin
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Push Docker image
      - name: Push Docker image
        run: |
          docker push thashenu/xox:build-$GITHUB_RUN_NUMBER

      # Step 5: Logout from Docker Hub (always run)
      - name: Logout from Docker Hub
        if: always()
        run: docker logout
